<?php

/*
 * @TODO: stacking support
 * @TODO: list icons
 * @TODO: tests
 *
 * */

namespace rsmike\fa;

/**
* @method static glass($options = null) Generates Glass icon
* @method static music($options = null) Generates Music icon
* @method static search($options = null) Generates Search icon
* @method static envelope_o($options = null) Generates Envelope Outlined icon
* @method static heart($options = null) Generates Heart icon
* @method static star($options = null) Generates Star icon
* @method static star_o($options = null) Generates Star Outlined icon
* @method static user($options = null) Generates User icon
* @method static film($options = null) Generates Film icon
* @method static th_large($options = null) Generates th-large icon
* @method static th($options = null) Generates th icon
* @method static th_list($options = null) Generates th-list icon
* @method static check($options = null) Generates Check icon
* @method static times($options = null) Generates Times icon
* @method static search_plus($options = null) Generates Search Plus icon
* @method static search_minus($options = null) Generates Search Minus icon
* @method static power_off($options = null) Generates Power Off icon
* @method static signal($options = null) Generates signal icon
* @method static cog($options = null) Generates cog icon
* @method static trash_o($options = null) Generates Trash Outlined icon
* @method static home($options = null) Generates home icon
* @method static file_o($options = null) Generates File Outlined icon
* @method static clock_o($options = null) Generates Clock Outlined icon
* @method static road($options = null) Generates road icon
* @method static download($options = null) Generates Download icon
* @method static arrow_circle_o_down($options = null) Generates Arrow Circle Outlined Down icon
* @method static arrow_circle_o_up($options = null) Generates Arrow Circle Outlined Up icon
* @method static inbox($options = null) Generates inbox icon
* @method static play_circle_o($options = null) Generates Play Circle Outlined icon
* @method static repeat($options = null) Generates Repeat icon
* @method static refresh($options = null) Generates refresh icon
* @method static list_alt($options = null) Generates list-alt icon
* @method static lock($options = null) Generates lock icon
* @method static flag($options = null) Generates flag icon
* @method static headphones($options = null) Generates headphones icon
* @method static volume_off($options = null) Generates volume-off icon
* @method static volume_down($options = null) Generates volume-down icon
* @method static volume_up($options = null) Generates volume-up icon
* @method static qrcode($options = null) Generates qrcode icon
* @method static barcode($options = null) Generates barcode icon
* @method static tag($options = null) Generates tag icon
* @method static tags($options = null) Generates tags icon
* @method static book($options = null) Generates book icon
* @method static bookmark($options = null) Generates bookmark icon
* @method static print($options = null) Generates print icon
* @method static camera($options = null) Generates camera icon
* @method static font($options = null) Generates font icon
* @method static bold($options = null) Generates bold icon
* @method static italic($options = null) Generates italic icon
* @method static text_height($options = null) Generates text-height icon
* @method static text_width($options = null) Generates text-width icon
* @method static align_left($options = null) Generates align-left icon
* @method static align_center($options = null) Generates align-center icon
* @method static align_right($options = null) Generates align-right icon
* @method static align_justify($options = null) Generates align-justify icon
* @method static list($options = null) Generates list icon
* @method static outdent($options = null) Generates Outdent icon
* @method static indent($options = null) Generates Indent icon
* @method static video_camera($options = null) Generates Video Camera icon
* @method static picture_o($options = null) Generates Picture Outlined icon
* @method static pencil($options = null) Generates pencil icon
* @method static map_marker($options = null) Generates map-marker icon
* @method static adjust($options = null) Generates adjust icon
* @method static tint($options = null) Generates tint icon
* @method static pencil_square_o($options = null) Generates Pencil Square Outlined icon
* @method static share_square_o($options = null) Generates Share Square Outlined icon
* @method static check_square_o($options = null) Generates Check Square Outlined icon
* @method static arrows($options = null) Generates Arrows icon
* @method static step_backward($options = null) Generates step-backward icon
* @method static fast_backward($options = null) Generates fast-backward icon
* @method static backward($options = null) Generates backward icon
* @method static play($options = null) Generates play icon
* @method static pause($options = null) Generates pause icon
* @method static stop($options = null) Generates stop icon
* @method static forward($options = null) Generates forward icon
* @method static fast_forward($options = null) Generates fast-forward icon
* @method static step_forward($options = null) Generates step-forward icon
* @method static eject($options = null) Generates eject icon
* @method static chevron_left($options = null) Generates chevron-left icon
* @method static chevron_right($options = null) Generates chevron-right icon
* @method static plus_circle($options = null) Generates Plus Circle icon
* @method static minus_circle($options = null) Generates Minus Circle icon
* @method static times_circle($options = null) Generates Times Circle icon
* @method static check_circle($options = null) Generates Check Circle icon
* @method static question_circle($options = null) Generates Question Circle icon
* @method static info_circle($options = null) Generates Info Circle icon
* @method static crosshairs($options = null) Generates Crosshairs icon
* @method static times_circle_o($options = null) Generates Times Circle Outlined icon
* @method static check_circle_o($options = null) Generates Check Circle Outlined icon
* @method static ban($options = null) Generates ban icon
* @method static arrow_left($options = null) Generates arrow-left icon
* @method static arrow_right($options = null) Generates arrow-right icon
* @method static arrow_up($options = null) Generates arrow-up icon
* @method static arrow_down($options = null) Generates arrow-down icon
* @method static share($options = null) Generates Share icon
* @method static expand($options = null) Generates Expand icon
* @method static compress($options = null) Generates Compress icon
* @method static plus($options = null) Generates plus icon
* @method static minus($options = null) Generates minus icon
* @method static asterisk($options = null) Generates asterisk icon
* @method static exclamation_circle($options = null) Generates Exclamation Circle icon
* @method static gift($options = null) Generates gift icon
* @method static leaf($options = null) Generates leaf icon
* @method static fire($options = null) Generates fire icon
* @method static eye($options = null) Generates Eye icon
* @method static eye_slash($options = null) Generates Eye Slash icon
* @method static exclamation_triangle($options = null) Generates Exclamation Triangle icon
* @method static plane($options = null) Generates plane icon
* @method static calendar($options = null) Generates calendar icon
* @method static random($options = null) Generates random icon
* @method static comment($options = null) Generates comment icon
* @method static magnet($options = null) Generates magnet icon
* @method static chevron_up($options = null) Generates chevron-up icon
* @method static chevron_down($options = null) Generates chevron-down icon
* @method static retweet($options = null) Generates retweet icon
* @method static shopping_cart($options = null) Generates shopping-cart icon
* @method static folder($options = null) Generates Folder icon
* @method static folder_open($options = null) Generates Folder Open icon
* @method static arrows_v($options = null) Generates Arrows Vertical icon
* @method static arrows_h($options = null) Generates Arrows Horizontal icon
* @method static bar_chart($options = null) Generates Bar Chart icon
* @method static twitter_square($options = null) Generates Twitter Square icon
* @method static facebook_square($options = null) Generates Facebook Square icon
* @method static camera_retro($options = null) Generates camera-retro icon
* @method static key($options = null) Generates key icon
* @method static cogs($options = null) Generates cogs icon
* @method static comments($options = null) Generates comments icon
* @method static thumbs_o_up($options = null) Generates Thumbs Up Outlined icon
* @method static thumbs_o_down($options = null) Generates Thumbs Down Outlined icon
* @method static star_half($options = null) Generates star-half icon
* @method static heart_o($options = null) Generates Heart Outlined icon
* @method static sign_out($options = null) Generates Sign Out icon
* @method static linkedin_square($options = null) Generates LinkedIn Square icon
* @method static thumb_tack($options = null) Generates Thumb Tack icon
* @method static external_link($options = null) Generates External Link icon
* @method static sign_in($options = null) Generates Sign In icon
* @method static trophy($options = null) Generates trophy icon
* @method static github_square($options = null) Generates GitHub Square icon
* @method static upload($options = null) Generates Upload icon
* @method static lemon_o($options = null) Generates Lemon Outlined icon
* @method static phone($options = null) Generates Phone icon
* @method static square_o($options = null) Generates Square Outlined icon
* @method static bookmark_o($options = null) Generates Bookmark Outlined icon
* @method static phone_square($options = null) Generates Phone Square icon
* @method static twitter($options = null) Generates Twitter icon
* @method static facebook($options = null) Generates Facebook icon
* @method static github($options = null) Generates GitHub icon
* @method static unlock($options = null) Generates unlock icon
* @method static credit_card($options = null) Generates credit-card icon
* @method static rss($options = null) Generates rss icon
* @method static hdd_o($options = null) Generates HDD icon
* @method static bullhorn($options = null) Generates bullhorn icon
* @method static bell($options = null) Generates bell icon
* @method static certificate($options = null) Generates certificate icon
* @method static hand_o_right($options = null) Generates Hand Outlined Right icon
* @method static hand_o_left($options = null) Generates Hand Outlined Left icon
* @method static hand_o_up($options = null) Generates Hand Outlined Up icon
* @method static hand_o_down($options = null) Generates Hand Outlined Down icon
* @method static arrow_circle_left($options = null) Generates Arrow Circle Left icon
* @method static arrow_circle_right($options = null) Generates Arrow Circle Right icon
* @method static arrow_circle_up($options = null) Generates Arrow Circle Up icon
* @method static arrow_circle_down($options = null) Generates Arrow Circle Down icon
* @method static globe($options = null) Generates Globe icon
* @method static wrench($options = null) Generates Wrench icon
* @method static tasks($options = null) Generates Tasks icon
* @method static filter($options = null) Generates Filter icon
* @method static briefcase($options = null) Generates Briefcase icon
* @method static arrows_alt($options = null) Generates Arrows Alt icon
* @method static users($options = null) Generates Users icon
* @method static link($options = null) Generates Link icon
* @method static cloud($options = null) Generates Cloud icon
* @method static flask($options = null) Generates Flask icon
* @method static scissors($options = null) Generates Scissors icon
* @method static files_o($options = null) Generates Files Outlined icon
* @method static paperclip($options = null) Generates Paperclip icon
* @method static floppy_o($options = null) Generates Floppy Outlined icon
* @method static square($options = null) Generates Square icon
* @method static bars($options = null) Generates Bars icon
* @method static list_ul($options = null) Generates list-ul icon
* @method static list_ol($options = null) Generates list-ol icon
* @method static strikethrough($options = null) Generates Strikethrough icon
* @method static underline($options = null) Generates Underline icon
* @method static table($options = null) Generates table icon
* @method static magic($options = null) Generates magic icon
* @method static truck($options = null) Generates truck icon
* @method static pinterest($options = null) Generates Pinterest icon
* @method static pinterest_square($options = null) Generates Pinterest Square icon
* @method static google_plus_square($options = null) Generates Google Plus Square icon
* @method static google_plus($options = null) Generates Google Plus icon
* @method static money($options = null) Generates Money icon
* @method static caret_down($options = null) Generates Caret Down icon
* @method static caret_up($options = null) Generates Caret Up icon
* @method static caret_left($options = null) Generates Caret Left icon
* @method static caret_right($options = null) Generates Caret Right icon
* @method static columns($options = null) Generates Columns icon
* @method static sort($options = null) Generates Sort icon
* @method static sort_desc($options = null) Generates Sort Descending icon
* @method static sort_asc($options = null) Generates Sort Ascending icon
* @method static envelope($options = null) Generates Envelope icon
* @method static linkedin($options = null) Generates LinkedIn icon
* @method static undo($options = null) Generates Undo icon
* @method static gavel($options = null) Generates Gavel icon
* @method static tachometer($options = null) Generates Tachometer icon
* @method static comment_o($options = null) Generates comment-o icon
* @method static comments_o($options = null) Generates comments-o icon
* @method static bolt($options = null) Generates Lightning Bolt icon
* @method static sitemap($options = null) Generates Sitemap icon
* @method static umbrella($options = null) Generates Umbrella icon
* @method static clipboard($options = null) Generates Clipboard icon
* @method static lightbulb_o($options = null) Generates Lightbulb Outlined icon
* @method static exchange($options = null) Generates Exchange icon
* @method static cloud_download($options = null) Generates Cloud Download icon
* @method static cloud_upload($options = null) Generates Cloud Upload icon
* @method static user_md($options = null) Generates user-md icon
* @method static stethoscope($options = null) Generates Stethoscope icon
* @method static suitcase($options = null) Generates Suitcase icon
* @method static bell_o($options = null) Generates Bell Outlined icon
* @method static coffee($options = null) Generates Coffee icon
* @method static cutlery($options = null) Generates Cutlery icon
* @method static file_text_o($options = null) Generates File Text Outlined icon
* @method static building_o($options = null) Generates Building Outlined icon
* @method static hospital_o($options = null) Generates hospital Outlined icon
* @method static ambulance($options = null) Generates ambulance icon
* @method static medkit($options = null) Generates medkit icon
* @method static fighter_jet($options = null) Generates fighter-jet icon
* @method static beer($options = null) Generates beer icon
* @method static h_square($options = null) Generates H Square icon
* @method static plus_square($options = null) Generates Plus Square icon
* @method static angle_double_left($options = null) Generates Angle Double Left icon
* @method static angle_double_right($options = null) Generates Angle Double Right icon
* @method static angle_double_up($options = null) Generates Angle Double Up icon
* @method static angle_double_down($options = null) Generates Angle Double Down icon
* @method static angle_left($options = null) Generates angle-left icon
* @method static angle_right($options = null) Generates angle-right icon
* @method static angle_up($options = null) Generates angle-up icon
* @method static angle_down($options = null) Generates angle-down icon
* @method static desktop($options = null) Generates Desktop icon
* @method static laptop($options = null) Generates Laptop icon
* @method static tablet($options = null) Generates tablet icon
* @method static mobile($options = null) Generates Mobile Phone icon
* @method static circle_o($options = null) Generates Circle Outlined icon
* @method static quote_left($options = null) Generates quote-left icon
* @method static quote_right($options = null) Generates quote-right icon
* @method static spinner($options = null) Generates Spinner icon
* @method static circle($options = null) Generates Circle icon
* @method static reply($options = null) Generates Reply icon
* @method static github_alt($options = null) Generates GitHub Alt icon
* @method static folder_o($options = null) Generates Folder Outlined icon
* @method static folder_open_o($options = null) Generates Folder Open Outlined icon
* @method static smile_o($options = null) Generates Smile Outlined icon
* @method static frown_o($options = null) Generates Frown Outlined icon
* @method static meh_o($options = null) Generates Meh Outlined icon
* @method static gamepad($options = null) Generates Gamepad icon
* @method static keyboard_o($options = null) Generates Keyboard Outlined icon
* @method static flag_o($options = null) Generates Flag Outlined icon
* @method static flag_checkered($options = null) Generates flag-checkered icon
* @method static terminal($options = null) Generates Terminal icon
* @method static code($options = null) Generates Code icon
* @method static reply_all($options = null) Generates reply-all icon
* @method static star_half_o($options = null) Generates Star Half Outlined icon
* @method static location_arrow($options = null) Generates location-arrow icon
* @method static crop($options = null) Generates crop icon
* @method static code_fork($options = null) Generates code-fork icon
* @method static chain_broken($options = null) Generates Chain Broken icon
* @method static question($options = null) Generates Question icon
* @method static info($options = null) Generates Info icon
* @method static exclamation($options = null) Generates exclamation icon
* @method static superscript($options = null) Generates superscript icon
* @method static subscript($options = null) Generates subscript icon
* @method static eraser($options = null) Generates eraser icon
* @method static puzzle_piece($options = null) Generates Puzzle Piece icon
* @method static microphone($options = null) Generates microphone icon
* @method static microphone_slash($options = null) Generates Microphone Slash icon
* @method static shield($options = null) Generates shield icon
* @method static calendar_o($options = null) Generates calendar-o icon
* @method static fire_extinguisher($options = null) Generates fire-extinguisher icon
* @method static rocket($options = null) Generates rocket icon
* @method static maxcdn($options = null) Generates MaxCDN icon
* @method static chevron_circle_left($options = null) Generates Chevron Circle Left icon
* @method static chevron_circle_right($options = null) Generates Chevron Circle Right icon
* @method static chevron_circle_up($options = null) Generates Chevron Circle Up icon
* @method static chevron_circle_down($options = null) Generates Chevron Circle Down icon
* @method static html5($options = null) Generates HTML 5 Logo icon
* @method static css3($options = null) Generates CSS 3 Logo icon
* @method static anchor($options = null) Generates Anchor icon
* @method static unlock_alt($options = null) Generates Unlock Alt icon
* @method static bullseye($options = null) Generates Bullseye icon
* @method static ellipsis_h($options = null) Generates Ellipsis Horizontal icon
* @method static ellipsis_v($options = null) Generates Ellipsis Vertical icon
* @method static rss_square($options = null) Generates RSS Square icon
* @method static play_circle($options = null) Generates Play Circle icon
* @method static ticket($options = null) Generates Ticket icon
* @method static minus_square($options = null) Generates Minus Square icon
* @method static minus_square_o($options = null) Generates Minus Square Outlined icon
* @method static level_up($options = null) Generates Level Up icon
* @method static level_down($options = null) Generates Level Down icon
* @method static check_square($options = null) Generates Check Square icon
* @method static pencil_square($options = null) Generates Pencil Square icon
* @method static external_link_square($options = null) Generates External Link Square icon
* @method static share_square($options = null) Generates Share Square icon
* @method static compass($options = null) Generates Compass icon
* @method static caret_square_o_down($options = null) Generates Caret Square Outlined Down icon
* @method static caret_square_o_up($options = null) Generates Caret Square Outlined Up icon
* @method static caret_square_o_right($options = null) Generates Caret Square Outlined Right icon
* @method static eur($options = null) Generates Euro (EUR) icon
* @method static gbp($options = null) Generates GBP icon
* @method static usd($options = null) Generates US Dollar icon
* @method static inr($options = null) Generates Indian Rupee (INR) icon
* @method static jpy($options = null) Generates Japanese Yen (JPY) icon
* @method static rub($options = null) Generates Russian Ruble (RUB) icon
* @method static krw($options = null) Generates Korean Won (KRW) icon
* @method static btc($options = null) Generates Bitcoin (BTC) icon
* @method static file($options = null) Generates File icon
* @method static file_text($options = null) Generates File Text icon
* @method static sort_alpha_asc($options = null) Generates Sort Alpha Ascending icon
* @method static sort_alpha_desc($options = null) Generates Sort Alpha Descending icon
* @method static sort_amount_asc($options = null) Generates Sort Amount Ascending icon
* @method static sort_amount_desc($options = null) Generates Sort Amount Descending icon
* @method static sort_numeric_asc($options = null) Generates Sort Numeric Ascending icon
* @method static sort_numeric_desc($options = null) Generates Sort Numeric Descending icon
* @method static thumbs_up($options = null) Generates thumbs-up icon
* @method static thumbs_down($options = null) Generates thumbs-down icon
* @method static youtube_square($options = null) Generates YouTube Square icon
* @method static youtube($options = null) Generates YouTube icon
* @method static xing($options = null) Generates Xing icon
* @method static xing_square($options = null) Generates Xing Square icon
* @method static youtube_play($options = null) Generates YouTube Play icon
* @method static dropbox($options = null) Generates Dropbox icon
* @method static stack_overflow($options = null) Generates Stack Overflow icon
* @method static instagram($options = null) Generates Instagram icon
* @method static flickr($options = null) Generates Flickr icon
* @method static adn($options = null) Generates App.net icon
* @method static bitbucket($options = null) Generates Bitbucket icon
* @method static bitbucket_square($options = null) Generates Bitbucket Square icon
* @method static tumblr($options = null) Generates Tumblr icon
* @method static tumblr_square($options = null) Generates Tumblr Square icon
* @method static long_arrow_down($options = null) Generates Long Arrow Down icon
* @method static long_arrow_up($options = null) Generates Long Arrow Up icon
* @method static long_arrow_left($options = null) Generates Long Arrow Left icon
* @method static long_arrow_right($options = null) Generates Long Arrow Right icon
* @method static apple($options = null) Generates Apple icon
* @method static windows($options = null) Generates Windows icon
* @method static android($options = null) Generates Android icon
* @method static linux($options = null) Generates Linux icon
* @method static dribbble($options = null) Generates Dribbble icon
* @method static skype($options = null) Generates Skype icon
* @method static foursquare($options = null) Generates Foursquare icon
* @method static trello($options = null) Generates Trello icon
* @method static female($options = null) Generates Female icon
* @method static male($options = null) Generates Male icon
* @method static gratipay($options = null) Generates Gratipay (Gittip) icon
* @method static sun_o($options = null) Generates Sun Outlined icon
* @method static moon_o($options = null) Generates Moon Outlined icon
* @method static archive($options = null) Generates Archive icon
* @method static bug($options = null) Generates Bug icon
* @method static vk($options = null) Generates VK icon
* @method static weibo($options = null) Generates Weibo icon
* @method static renren($options = null) Generates Renren icon
* @method static pagelines($options = null) Generates Pagelines icon
* @method static stack_exchange($options = null) Generates Stack Exchange icon
* @method static arrow_circle_o_right($options = null) Generates Arrow Circle Outlined Right icon
* @method static arrow_circle_o_left($options = null) Generates Arrow Circle Outlined Left icon
* @method static caret_square_o_left($options = null) Generates Caret Square Outlined Left icon
* @method static dot_circle_o($options = null) Generates Dot Circle Outlined icon
* @method static wheelchair($options = null) Generates Wheelchair icon
* @method static vimeo_square($options = null) Generates Vimeo Square icon
* @method static try($options = null) Generates Turkish Lira (TRY) icon
* @method static plus_square_o($options = null) Generates Plus Square Outlined icon
* @method static space_shuttle($options = null) Generates Space Shuttle icon
* @method static slack($options = null) Generates Slack Logo icon
* @method static envelope_square($options = null) Generates Envelope Square icon
* @method static wordpress($options = null) Generates WordPress Logo icon
* @method static openid($options = null) Generates OpenID icon
* @method static university($options = null) Generates University icon
* @method static graduation_cap($options = null) Generates Graduation Cap icon
* @method static yahoo($options = null) Generates Yahoo Logo icon
* @method static google($options = null) Generates Google Logo icon
* @method static reddit($options = null) Generates reddit Logo icon
* @method static reddit_square($options = null) Generates reddit Square icon
* @method static stumbleupon_circle($options = null) Generates StumbleUpon Circle icon
* @method static stumbleupon($options = null) Generates StumbleUpon Logo icon
* @method static delicious($options = null) Generates Delicious Logo icon
* @method static digg($options = null) Generates Digg Logo icon
* @method static pied_piper_pp($options = null) Generates Pied Piper PP Logo (Old) icon
* @method static pied_piper_alt($options = null) Generates Pied Piper Alternate Logo icon
* @method static drupal($options = null) Generates Drupal Logo icon
* @method static joomla($options = null) Generates Joomla Logo icon
* @method static language($options = null) Generates Language icon
* @method static fax($options = null) Generates Fax icon
* @method static building($options = null) Generates Building icon
* @method static child($options = null) Generates Child icon
* @method static paw($options = null) Generates Paw icon
* @method static spoon($options = null) Generates spoon icon
* @method static cube($options = null) Generates Cube icon
* @method static cubes($options = null) Generates Cubes icon
* @method static behance($options = null) Generates Behance icon
* @method static behance_square($options = null) Generates Behance Square icon
* @method static steam($options = null) Generates Steam icon
* @method static steam_square($options = null) Generates Steam Square icon
* @method static recycle($options = null) Generates Recycle icon
* @method static car($options = null) Generates Car icon
* @method static taxi($options = null) Generates Taxi icon
* @method static tree($options = null) Generates Tree icon
* @method static spotify($options = null) Generates Spotify icon
* @method static deviantart($options = null) Generates deviantART icon
* @method static soundcloud($options = null) Generates SoundCloud icon
* @method static database($options = null) Generates Database icon
* @method static file_pdf_o($options = null) Generates PDF File Outlined icon
* @method static file_word_o($options = null) Generates Word File Outlined icon
* @method static file_excel_o($options = null) Generates Excel File Outlined icon
* @method static file_powerpoint_o($options = null) Generates Powerpoint File Outlined icon
* @method static file_image_o($options = null) Generates Image File Outlined icon
* @method static file_archive_o($options = null) Generates Archive File Outlined icon
* @method static file_audio_o($options = null) Generates Audio File Outlined icon
* @method static file_video_o($options = null) Generates Video File Outlined icon
* @method static file_code_o($options = null) Generates Code File Outlined icon
* @method static vine($options = null) Generates Vine icon
* @method static codepen($options = null) Generates Codepen icon
* @method static jsfiddle($options = null) Generates jsFiddle icon
* @method static life_ring($options = null) Generates Life Ring icon
* @method static circle_o_notch($options = null) Generates Circle Outlined Notched icon
* @method static rebel($options = null) Generates Rebel Alliance icon
* @method static empire($options = null) Generates Galactic Empire icon
* @method static git_square($options = null) Generates Git Square icon
* @method static git($options = null) Generates Git icon
* @method static hacker_news($options = null) Generates Hacker News icon
* @method static tencent_weibo($options = null) Generates Tencent Weibo icon
* @method static qq($options = null) Generates QQ icon
* @method static weixin($options = null) Generates Weixin (WeChat) icon
* @method static paper_plane($options = null) Generates Paper Plane icon
* @method static paper_plane_o($options = null) Generates Paper Plane Outlined icon
* @method static history($options = null) Generates History icon
* @method static circle_thin($options = null) Generates Circle Outlined Thin icon
* @method static header($options = null) Generates header icon
* @method static paragraph($options = null) Generates paragraph icon
* @method static sliders($options = null) Generates Sliders icon
* @method static share_alt($options = null) Generates Share Alt icon
* @method static share_alt_square($options = null) Generates Share Alt Square icon
* @method static bomb($options = null) Generates Bomb icon
* @method static futbol_o($options = null) Generates Futbol Outlined icon
* @method static tty($options = null) Generates TTY icon
* @method static binoculars($options = null) Generates Binoculars icon
* @method static plug($options = null) Generates Plug icon
* @method static slideshare($options = null) Generates Slideshare icon
* @method static twitch($options = null) Generates Twitch icon
* @method static yelp($options = null) Generates Yelp icon
* @method static newspaper_o($options = null) Generates Newspaper Outlined icon
* @method static wifi($options = null) Generates WiFi icon
* @method static calculator($options = null) Generates Calculator icon
* @method static paypal($options = null) Generates Paypal icon
* @method static google_wallet($options = null) Generates Google Wallet icon
* @method static cc_visa($options = null) Generates Visa Credit Card icon
* @method static cc_mastercard($options = null) Generates MasterCard Credit Card icon
* @method static cc_discover($options = null) Generates Discover Credit Card icon
* @method static cc_amex($options = null) Generates American Express Credit Card icon
* @method static cc_paypal($options = null) Generates Paypal Credit Card icon
* @method static cc_stripe($options = null) Generates Stripe Credit Card icon
* @method static bell_slash($options = null) Generates Bell Slash icon
* @method static bell_slash_o($options = null) Generates Bell Slash Outlined icon
* @method static trash($options = null) Generates Trash icon
* @method static copyright($options = null) Generates Copyright icon
* @method static at($options = null) Generates At icon
* @method static eyedropper($options = null) Generates Eyedropper icon
* @method static paint_brush($options = null) Generates Paint Brush icon
* @method static birthday_cake($options = null) Generates Birthday Cake icon
* @method static area_chart($options = null) Generates Area Chart icon
* @method static pie_chart($options = null) Generates Pie Chart icon
* @method static line_chart($options = null) Generates Line Chart icon
* @method static lastfm($options = null) Generates last.fm icon
* @method static lastfm_square($options = null) Generates last.fm Square icon
* @method static toggle_off($options = null) Generates Toggle Off icon
* @method static toggle_on($options = null) Generates Toggle On icon
* @method static bicycle($options = null) Generates Bicycle icon
* @method static bus($options = null) Generates Bus icon
* @method static ioxhost($options = null) Generates ioxhost icon
* @method static angellist($options = null) Generates AngelList icon
* @method static cc($options = null) Generates Closed Captions icon
* @method static ils($options = null) Generates Shekel (ILS) icon
* @method static meanpath($options = null) Generates meanpath icon
* @method static buysellads($options = null) Generates BuySellAds icon
* @method static connectdevelop($options = null) Generates Connect Develop icon
* @method static dashcube($options = null) Generates DashCube icon
* @method static forumbee($options = null) Generates Forumbee icon
* @method static leanpub($options = null) Generates Leanpub icon
* @method static sellsy($options = null) Generates Sellsy icon
* @method static shirtsinbulk($options = null) Generates Shirts in Bulk icon
* @method static simplybuilt($options = null) Generates SimplyBuilt icon
* @method static skyatlas($options = null) Generates skyatlas icon
* @method static cart_plus($options = null) Generates Add to Shopping Cart icon
* @method static cart_arrow_down($options = null) Generates Shopping Cart Arrow Down icon
* @method static diamond($options = null) Generates Diamond icon
* @method static ship($options = null) Generates Ship icon
* @method static user_secret($options = null) Generates User Secret icon
* @method static motorcycle($options = null) Generates Motorcycle icon
* @method static street_view($options = null) Generates Street View icon
* @method static heartbeat($options = null) Generates Heartbeat icon
* @method static venus($options = null) Generates Venus icon
* @method static mars($options = null) Generates Mars icon
* @method static mercury($options = null) Generates Mercury icon
* @method static transgender($options = null) Generates Transgender icon
* @method static transgender_alt($options = null) Generates Transgender Alt icon
* @method static venus_double($options = null) Generates Venus Double icon
* @method static mars_double($options = null) Generates Mars Double icon
* @method static venus_mars($options = null) Generates Venus Mars icon
* @method static mars_stroke($options = null) Generates Mars Stroke icon
* @method static mars_stroke_v($options = null) Generates Mars Stroke Vertical icon
* @method static mars_stroke_h($options = null) Generates Mars Stroke Horizontal icon
* @method static neuter($options = null) Generates Neuter icon
* @method static genderless($options = null) Generates Genderless icon
* @method static facebook_official($options = null) Generates Facebook Official icon
* @method static pinterest_p($options = null) Generates Pinterest P icon
* @method static whatsapp($options = null) Generates What's App icon
* @method static server($options = null) Generates Server icon
* @method static user_plus($options = null) Generates Add User icon
* @method static user_times($options = null) Generates Remove User icon
* @method static bed($options = null) Generates Bed icon
* @method static viacoin($options = null) Generates Viacoin icon
* @method static train($options = null) Generates Train icon
* @method static subway($options = null) Generates Subway icon
* @method static medium($options = null) Generates Medium icon
* @method static y_combinator($options = null) Generates Y Combinator icon
* @method static optin_monster($options = null) Generates Optin Monster icon
* @method static opencart($options = null) Generates OpenCart icon
* @method static expeditedssl($options = null) Generates ExpeditedSSL icon
* @method static battery_full($options = null) Generates Battery Full icon
* @method static battery_three_quarters($options = null) Generates Battery 3/4 Full icon
* @method static battery_half($options = null) Generates Battery 1/2 Full icon
* @method static battery_quarter($options = null) Generates Battery 1/4 Full icon
* @method static battery_empty($options = null) Generates Battery Empty icon
* @method static mouse_pointer($options = null) Generates Mouse Pointer icon
* @method static i_cursor($options = null) Generates I Beam Cursor icon
* @method static object_group($options = null) Generates Object Group icon
* @method static object_ungroup($options = null) Generates Object Ungroup icon
* @method static sticky_note($options = null) Generates Sticky Note icon
* @method static sticky_note_o($options = null) Generates Sticky Note Outlined icon
* @method static cc_jcb($options = null) Generates JCB Credit Card icon
* @method static cc_diners_club($options = null) Generates Diner's Club Credit Card icon
* @method static clone($options = null) Generates Clone icon
* @method static balance_scale($options = null) Generates Balance Scale icon
* @method static hourglass_o($options = null) Generates Hourglass Outlined icon
* @method static hourglass_start($options = null) Generates Hourglass Start icon
* @method static hourglass_half($options = null) Generates Hourglass Half icon
* @method static hourglass_end($options = null) Generates Hourglass End icon
* @method static hourglass($options = null) Generates Hourglass icon
* @method static hand_rock_o($options = null) Generates Rock (Hand) icon
* @method static hand_paper_o($options = null) Generates Paper (Hand) icon
* @method static hand_scissors_o($options = null) Generates Scissors (Hand) icon
* @method static hand_lizard_o($options = null) Generates Lizard (Hand) icon
* @method static hand_spock_o($options = null) Generates Spock (Hand) icon
* @method static hand_pointer_o($options = null) Generates Hand Pointer icon
* @method static hand_peace_o($options = null) Generates Hand Peace icon
* @method static trademark($options = null) Generates Trademark icon
* @method static registered($options = null) Generates Registered Trademark icon
* @method static creative_commons($options = null) Generates Creative Commons icon
* @method static gg($options = null) Generates GG Currency icon
* @method static gg_circle($options = null) Generates GG Currency Circle icon
* @method static tripadvisor($options = null) Generates TripAdvisor icon
* @method static odnoklassniki($options = null) Generates Odnoklassniki icon
* @method static odnoklassniki_square($options = null) Generates Odnoklassniki Square icon
* @method static get_pocket($options = null) Generates Get Pocket icon
* @method static wikipedia_w($options = null) Generates Wikipedia W icon
* @method static safari($options = null) Generates Safari icon
* @method static chrome($options = null) Generates Chrome icon
* @method static firefox($options = null) Generates Firefox icon
* @method static opera($options = null) Generates Opera icon
* @method static internet_explorer($options = null) Generates Internet-explorer icon
* @method static television($options = null) Generates Television icon
* @method static contao($options = null) Generates Contao icon
* @method static 500px($options = null) Generates 500px icon
* @method static amazon($options = null) Generates Amazon icon
* @method static calendar_plus_o($options = null) Generates Calendar Plus Outlined icon
* @method static calendar_minus_o($options = null) Generates Calendar Minus Outlined icon
* @method static calendar_times_o($options = null) Generates Calendar Times Outlined icon
* @method static calendar_check_o($options = null) Generates Calendar Check Outlined icon
* @method static industry($options = null) Generates Industry icon
* @method static map_pin($options = null) Generates Map Pin icon
* @method static map_signs($options = null) Generates Map Signs icon
* @method static map_o($options = null) Generates Map Outlined icon
* @method static map($options = null) Generates Map icon
* @method static commenting($options = null) Generates Commenting icon
* @method static commenting_o($options = null) Generates Commenting Outlined icon
* @method static houzz($options = null) Generates Houzz icon
* @method static vimeo($options = null) Generates Vimeo icon
* @method static black_tie($options = null) Generates Font Awesome Black Tie icon
* @method static fonticons($options = null) Generates Fonticons icon
* @method static reddit_alien($options = null) Generates reddit Alien icon
* @method static edge($options = null) Generates Edge Browser icon
* @method static credit_card_alt($options = null) Generates Credit Card icon
* @method static codiepie($options = null) Generates Codie Pie icon
* @method static modx($options = null) Generates MODX icon
* @method static fort_awesome($options = null) Generates Fort Awesome icon
* @method static usb($options = null) Generates USB icon
* @method static product_hunt($options = null) Generates Product Hunt icon
* @method static mixcloud($options = null) Generates Mixcloud icon
* @method static scribd($options = null) Generates Scribd icon
* @method static pause_circle($options = null) Generates Pause Circle icon
* @method static pause_circle_o($options = null) Generates Pause Circle Outlined icon
* @method static stop_circle($options = null) Generates Stop Circle icon
* @method static stop_circle_o($options = null) Generates Stop Circle Outlined icon
* @method static shopping_bag($options = null) Generates Shopping Bag icon
* @method static shopping_basket($options = null) Generates Shopping Basket icon
* @method static hashtag($options = null) Generates Hashtag icon
* @method static bluetooth($options = null) Generates Bluetooth icon
* @method static bluetooth_b($options = null) Generates Bluetooth icon
* @method static percent($options = null) Generates Percent icon
* @method static gitlab($options = null) Generates GitLab icon
* @method static wpbeginner($options = null) Generates WPBeginner icon
* @method static wpforms($options = null) Generates WPForms icon
* @method static envira($options = null) Generates Envira Gallery icon
* @method static universal_access($options = null) Generates Universal Access icon
* @method static wheelchair_alt($options = null) Generates Wheelchair Alt icon
* @method static question_circle_o($options = null) Generates Question Circle Outlined icon
* @method static blind($options = null) Generates Blind icon
* @method static audio_description($options = null) Generates Audio Description icon
* @method static volume_control_phone($options = null) Generates Volume Control Phone icon
* @method static braille($options = null) Generates Braille icon
* @method static assistive_listening_systems($options = null) Generates Assistive Listening Systems icon
* @method static american_sign_language_interpreting($options = null) Generates American Sign Language Interpreting icon
* @method static deaf($options = null) Generates Deaf icon
* @method static glide($options = null) Generates Glide icon
* @method static glide_g($options = null) Generates Glide G icon
* @method static sign_language($options = null) Generates Sign Language icon
* @method static low_vision($options = null) Generates Low Vision icon
* @method static viadeo($options = null) Generates Viadeo icon
* @method static viadeo_square($options = null) Generates Viadeo Square icon
* @method static snapchat($options = null) Generates Snapchat icon
* @method static snapchat_ghost($options = null) Generates Snapchat Ghost icon
* @method static snapchat_square($options = null) Generates Snapchat Square icon
* @method static pied_piper($options = null) Generates Pied Piper Logo icon
* @method static first_order($options = null) Generates First Order icon
* @method static yoast($options = null) Generates Yoast icon
* @method static themeisle($options = null) Generates ThemeIsle icon
* @method static google_plus_official($options = null) Generates Google Plus Official icon
* @method static font_awesome($options = null) Generates Font Awesome icon
* @method static handshake_o($options = null) Generates Handshake Outlined icon
* @method static envelope_open($options = null) Generates Envelope Open icon
* @method static envelope_open_o($options = null) Generates Envelope Open Outlined icon
* @method static linode($options = null) Generates Linode icon
* @method static address_book($options = null) Generates Address Book icon
* @method static address_book_o($options = null) Generates Address Book Outlined icon
* @method static address_card($options = null) Generates Address Card icon
* @method static address_card_o($options = null) Generates Address Card Outlined icon
* @method static user_circle($options = null) Generates User Circle icon
* @method static user_circle_o($options = null) Generates User Circle Outlined icon
* @method static user_o($options = null) Generates User Outlined icon
* @method static id_badge($options = null) Generates Identification Badge icon
* @method static id_card($options = null) Generates Identification Card icon
* @method static id_card_o($options = null) Generates Identification Card Outlined icon
* @method static quora($options = null) Generates Quora icon
* @method static free_code_camp($options = null) Generates Free Code Camp icon
* @method static telegram($options = null) Generates Telegram icon
* @method static thermometer_full($options = null) Generates Thermometer Full icon
* @method static thermometer_three_quarters($options = null) Generates Thermometer 3/4 Full icon
* @method static thermometer_half($options = null) Generates Thermometer 1/2 Full icon
* @method static thermometer_quarter($options = null) Generates Thermometer 1/4 Full icon
* @method static thermometer_empty($options = null) Generates Thermometer Empty icon
* @method static shower($options = null) Generates Shower icon
* @method static bath($options = null) Generates Bath icon
* @method static podcast($options = null) Generates Podcast icon
* @method static window_maximize($options = null) Generates Window Maximize icon
* @method static window_minimize($options = null) Generates Window Minimize icon
* @method static window_restore($options = null) Generates Window Restore icon
* @method static window_close($options = null) Generates Window Close icon
* @method static window_close_o($options = null) Generates Window Close Outline icon
* @method static bandcamp($options = null) Generates Bandcamp icon
* @method static grav($options = null) Generates Grav icon
* @method static etsy($options = null) Generates Etsy icon
* @method static imdb($options = null) Generates IMDB icon
* @method static ravelry($options = null) Generates Ravelry icon
* @method static eercast($options = null) Generates Eercast icon
* @method static microchip($options = null) Generates Microchip icon
* @method static snowflake_o($options = null) Generates Snowflake Outlined icon
* @method static superpowers($options = null) Generates Superpowers icon
* @method static wpexplorer($options = null) Generates WPExplorer icon
* @method static meetup($options = null) Generates Meetup icon
 **/

class FA
{
    /* Initial setup */
    public static $iconAlias = [];
    public static $defaultOptions = self::SPACE;

    const SPACE         = 0b000000000000000000000001;

    const PULL_LEFT     = 0b000000000000000000000010;
    const PULL_RIGHT    = 0b000000000000000000000100;
    const SIZE_LG       = 0b000000000000000000001000;
    const SIZE_2X       = 0b000000000000000000010000;
    const SIZE_3X       = 0b000000000000000000100000;
    const SIZE_4X       = 0b000000000000000001000000;
    const SIZE_5X       = 0b000000000000000010000000;
    const FIX_WIDTH     = 0b000000000000000100000000;
    const INVERSE       = 0b000000000000001000000000;
    const BORDER        = 0b000000000000010000000000;
    const SPIN          = 0b000000000000100000000000;
    const PULSE         = 0b000000000001000000000000;
    const ROT90         = 0b000000000010000000000000;
    const ROT180        = 0b000000000100000000000000;
    const ROT270        = 0b000000001000000000000000;
    const FLIP_V        = 0b000000010000000000000000;
    const FLIP_H        = 0b000000100000000000000000;

    private $name;
    private $class;
    private $css;
    private $options;

    private static $faClasses = [
        self::PULL_LEFT => 'fa-pull-left',
        self::PULL_RIGHT => 'fa-pull-right',
        self::SIZE_LG => 'fa-lg',
        self::SIZE_2X => 'fa-2x',
        self::SIZE_3X => 'fa-3x',
        self::SIZE_4X => 'fa-4x',
        self::SIZE_5X => 'fa-5x',
        self::FIX_WIDTH => 'fa-fw',
        self::INVERSE => 'fa-inverse',
        self::BORDER => 'fa-border',
        self::SPIN => 'fa-spin',
        self::PULSE => 'fa-pulse',
        self::ROT90 => 'fa-rotate-90',
        self::ROT180 => 'fa-rotate-180',
        self::ROT270 => 'fa-rotate-270',
        self::FLIP_V => 'fa-flip-horizontal',
        self::FLIP_H => 'fa-flip-vertical',
    ];

    public function __toString() {
        $classes = ['fa'];
        $classes[] = $this->name;

        foreach (self::$faClasses as $flag=>$faClass) {
            if ($this->options & $flag) {
                $classes[] = $faClass;
            }
        }

        if ($this->class) {
            $classes[] = $this->class;
        }

        return '<i class="'.join(' ',$classes).($this->css?'" style="'.$this->css:'').'"></i>'.($this->options & self::SPACE?' ':'');
    }

    public function __construct($icon = '', $options = null) {
        $this->name = self::$iconAlias[$icon] ?? $icon;
        $this->options = $options ?? self::$defaultOptions;
    }

    public function set($options) {
        $this->options = $options;
        return $this;
    }

    public function css($css) {
        $this->css = $css;
        return $this;
    }

    public function class($class) {
        $this->class = $class;
        return $this;
    }

    /**
     * Shortcut static constructor for Font Awesome icons
     *
     * @param string $name function name is icon name
     * @param array $arguments argument[0] for options
     * @return string
     */
    public static function __callStatic($name, $arguments) {
        return (new self(str_replace('_','-',$name)))->set(...$arguments);
    }
}